// react-app-env.d.ts
// ----------------------------------------------------
// This file is an environment file automatically generated by Create React App (CRA)
// when using TypeScript. It includes important type definitions that ensure proper
// type-checking in the application.
//
// The directive below references the built-in type definitions provided by `react-scripts`.
// These types include:
// 1. Global JSX types required for React components.
// 2. Types for environment variables (e.g., `process.env.REACT_APP_*`).
// 3. Other utility types used in a standard Create React App setup.
//
// Typically, you should not modify this file unless you are making significant
// changes to the CRA setup or migrating away from CRA.
//
// Reference Directive:
// The `/// <reference types="react-scripts" />` directive below allows TypeScript
// to recognize the types and utilities provided by `react-scripts`. Removing or
// altering this reference can lead to issues with TypeScript's type-checking
// and may cause errors in your app.
// ----------------------------------------------------

/// <reference types="react-scripts" />
